title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs@v0.5.1
logo: "/assets/images/logo.svg"
enable_copy_code_button: true

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template  

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

callouts:
  warning:
    title: Warning
    color: red
  example:
    title: Exemples
    color: grey-dk
  request-get:
    title: GET
    color: green
  request-post:
    title: POST
    color: yellow
  request-put:
    title: PUT
    color: blue
  request-delete:
    title: DELETE
    color: red
