title: Sharlotte API
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs@v0.5.1
logo: "/assets/images/logo.svg"
enable_copy_code_button: true

url: https://doc.sharlotte.fr/

aux_links:
  Sharlotte: https://sharlotte.fr/ 

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
      
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.1.0"

callouts:
  warning:
    title: Warning
    color: red
  example:
    title: Exemples
    color: grey-dk
  note:
    title: Note
    color: purple
  request-get:
    title: GET
    color: green
  request-post:
    title: POST
    color: yellow
  request-put:
    title: PUT
    color: blue
  request-delete:
    title: DELETE
    color: red
